### ISSUE TITLE
디자인 원칙 (DIP, Dependency Injection Principle)

### ISSUE THREAD

**Issue by dlfranks** [IT-Book-Organization/HeadFirst-DesignPattern#11]
요즘 이 리포를 이용해서 공부하고있습니다. 공부중에 버그를 발견해서 알려드립니다.
디자인 원칙 (DIP, Dependency Injection Principle) => Dependency Inversion Principle
요약해 주셔서 감사합니다.

**Comment by eunaJung01** [comment]
말씀해주신 부분 수정하였습니다! 감사합니다 👍👍
