### ISSUE TITLE
[Chapter 1. 전략 패턴] 전략 패턴은 전략의 변경 여지가 없다

### ISSUE THREAD

**Issue by eunaJung01** [IT-Book-Organization/HeadFirst-DesignPattern#3]
[Chapter 1. 전략 패턴](https://github.com/IT-Book-Organization/HeadFirst-DesignPattern/blob/main/Chapter1/README.md)에서 전략 패턴의 단점으로 <b>‘전략의 변경 여지가 없다’</b>고 적어주셨는데, 의미가 잘 이해되질 않습니다 🥲

전략 패턴의 장점은 새로운 전략이 추가되거나 수정되어도 **컨텍스트의 코드 변경 없이도 새로운 전략을 추가 또는 수정할 수 있기 때문에**  
코드 변경에 매우 유연하여 개방-폐쇄 원칙(OCP)을 지킬 수 있다는 것으로 이해하고 있었습니다.

왜 전략 패턴이 전략의 변경 여지가 없게 만드는 것인가요??

**Comment by jung-woo-kim** [comment]
전략의 변경 여지가 없을 때, 전략 패턴의 사용이 코드의 복잡성을 증가시킬 수 있다는 의미였습니다. 🙂
